"""Policy imitation experiments kept separate from the established agents."""

from .bc_network import BehaviorCloningNetwork
from .bc_training import BCConfig, evaluate_bc_model, load_bc_checkpoint, train_bc
from .dagger import (
    aggregate_dagger_datasets,
    collect_dagger_dataset,
    play_dagger_game,
    summarize_dagger_records,
)
from .manifest import (
    DEFAULT_FORBIDDEN_SEED_RANGES,
    approve_manifest,
    create_manifest,
    load_manifest,
    require_approved,
    validate_manifest,
)
from .policies import (
    CandidateSpec,
    build_bc_candidate,
    build_builtin_candidate,
    build_fixed_baseline,
)
from .ppo_selfplay import (
    OpponentPoolEntry,
    PolicyValueNetwork,
    PPOConfig,
    PPOPolicyAgent,
    PPOTransition,
    build_policy_candidate,
    collect_ppo_game,
    compute_gae,
    load_ppo_checkpoint,
    ppo_update,
    save_ppo_checkpoint,
    train_ppo_selfplay,
)
from .protocol import (
    RuntimeSnapshot,
    capture_code_revision,
    isolated_seed,
    seed_everything,
)
from .scenario import (
    ScenarioV1,
    action_registry_hash,
    card_registry_hash,
    generate_scenario,
    rule_from_scenario,
    state_from_scenario,
)
from .scenario_bank import (
    ScenarioBank,
    consume_sealed_scenario_bank,
    generate_iid_scenarios,
    load_scenario_bank,
    load_scenario_bank_subset,
    write_scenario_bank,
)
from .trajectory import (
    TrajectoryDataset,
    TrajectoryStep,
    concatenate_datasets,
    split_by_seed,
)

__all__ = [
    "DEFAULT_FORBIDDEN_SEED_RANGES",
    "BCConfig",
    "BehaviorCloningNetwork",
    "CandidateSpec",
    "OpponentPoolEntry",
    "PPOConfig",
    "PPOPolicyAgent",
    "PPOTransition",
    "PolicyValueNetwork",
    "RuntimeSnapshot",
    "ScenarioBank",
    "ScenarioV1",
    "TrajectoryDataset",
    "TrajectoryStep",
    "action_registry_hash",
    "aggregate_dagger_datasets",
    "approve_manifest",
    "build_bc_candidate",
    "build_builtin_candidate",
    "build_fixed_baseline",
    "build_policy_candidate",
    "capture_code_revision",
    "card_registry_hash",
    "collect_dagger_dataset",
    "collect_ppo_game",
    "compute_gae",
    "concatenate_datasets",
    "consume_sealed_scenario_bank",
    "create_manifest",
    "evaluate_bc_model",
    "generate_iid_scenarios",
    "generate_scenario",
    "isolated_seed",
    "load_bc_checkpoint",
    "load_manifest",
    "load_ppo_checkpoint",
    "load_scenario_bank",
    "load_scenario_bank_subset",
    "play_dagger_game",
    "ppo_update",
    "require_approved",
    "rule_from_scenario",
    "save_ppo_checkpoint",
    "seed_everything",
    "split_by_seed",
    "state_from_scenario",
    "summarize_dagger_records",
    "train_bc",
    "train_ppo_selfplay",
    "validate_manifest",
    "write_scenario_bank",
]
